include:
  - network.yaml

services:
  postgresql:
    container_name: postgresql
    image: ${PG_IMAGE}
    ports:
      - "${PG_PORT}:5432"
    environment:
      TZ: ${PG_TZ}
      PGTZ: ${PG_TZ}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    external: true
    name: local-postgre
