include:
  - network.yaml

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: wOS-development
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: zoka01-alpha.w6.co:9092,zoka02-alpha.w6.co:9092,zoka03-alpha.w6.co:9092
      KAFKA_CLUSTERS_1_NAME: confluentinc
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: confluent-broker:9092
      KAFKA_CLUSTERS_2_NAME: cluster-confluentinc
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: confluent-kafka-1:9092,confluent-kafka-2:9092,confluent-kafka-3:9092
    ports:
      - "8000:8080"
    networks:
      - kafka-cluster
      - kafka-single-node
