include:
  - network.yaml

services:
  mysql:
    image: ${MYSQL_IMAGE}
    container_name: mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TZ=${MYSQL_TZ}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    external: true
    name: local-mysql
