include:
  - network.yaml

services:
  n8n:
    container_name: n8n
    image: ${N8N_IMAGE}
    ports:
      - ${N8N_PORT}:${N8N_PORT}
    volumes:
      - n8n-data:/home/node/.n8n
      - n8n-log:/var/log/n8n
    environment:
      - NODE_ENV=${NODE_ENV}
      - N8N_PORT=${N8N_PORT}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=http://${N8N_HOST}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
      - DB_TYPE=${N8N_DB_TYPE}
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=${N8N_POSTGRES_PORT}
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_DATABASE=${N8N_POSTGRES_DATABASE}
      - DB_POSTGRESDB_USER=${N8N_POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - GENERIC_TIMEZONE=${N8N_POSTGRES_TIMEZONE}
      - TZ=${N8N_POSTGRES_TIMEZONE}
      - N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED}
      - N8N_RUNNERS_MODE=${N8N_RUNNERS_MODE}
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
    depends_on:
      - n8n-postgres
    networks:
      - n8n
      - nginx-reverse-proxy

  n8n-runner:
    container_name: n8n-runner
    image: ${N8N_RUNNER_IMAGE}
    restart: always
    environment:
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
      - N8N_RUNNERS_HOST=${N8N_RUNNERS_HOST}
      - N8N_RUNNERS_PORT=${N8N_RUNNERS_PORT}
    depends_on:
      - n8n
    networks:
      - n8n

  n8n-postgres:
    container_name: n8n-postgres
    image: ${N8N_POSTGRES_IMAGE}
    volumes:
      - n8n-postgres-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${N8N_POSTGRES_DATABASE}
      - POSTGRESQL_PORT_NUMBER=${N8N_POSTGRES_PORT}
      - POSTGRESQL_USERNAME=${N8N_POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - POSTGRESQL_TIMEZONE=${N8N_POSTGRES_TIMEZONE}
    networks:
      - n8n

volumes:
  n8n-data:
    external: true
    name: local-data-n8n
  n8n-log:
    external: true
    name: local-log-n8n
  n8n-postgres-data:
    external: true
    name: local-data-n8n-postgres
