include:
  - network.yaml

services:
  confluent-zookeeper-1:
    image: confluentinc/cp-zookeeper:6.1.0
    container_name: confluent-zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
    volumes:
      - cluster-zookeeper-1:/var/lib/zookeeper/data
      - cluster-zookeeper-log-1:/var/lib/zookeeper/log

  confluent-zookeeper-2:
    image: confluentinc/cp-zookeeper:6.1.0
    container_name: confluent-zookeeper-2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 2
    volumes:
      - cluster-zookeeper-2:/var/lib/zookeeper/data
      - cluster-zookeeper-log-2:/var/lib/zookeeper/log

  confluent-kafka-1:
    image: confluentinc/cp-kafka:6.1.0
    container_name: confluent-kafka-1
    depends_on:
      - confluent-zookeeper-1
      - confluent-zookeeper-2
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "confluent-zookeeper-1:2181,confluent-zookeeper-2:2182"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://confluent-kafka-1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - cluster-kafka-data-1:/var/lib/kafka/data
      - cluster-kafka-log-1:/var/log/kafka
      - cluster-kafka-etc-1:/etc/kafka # make sure the cluster is not changing

  confluent-kafka-2:
    image: confluentinc/cp-kafka:6.1.0
    container_name: confluent-kafka-2
    depends_on:
      - confluent-zookeeper-1
      - confluent-zookeeper-2
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "confluent-zookeeper-1:2181,confluent-zookeeper-2:2182"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://confluent-kafka-2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - cluster-kafka-data-2:/var/lib/kafka/data
      - cluster-kafka-log-2:/var/log/kafka
      - cluster-kafka-etc-2:/etc/kafka # make sure the cluster is not changing

volumes:
  cluster-kafka-data-1:
  cluster-kafka-log-1:
  cluster-kafka-etc-1:
  cluster-kafka-data-2:
  cluster-kafka-log-2:
  cluster-kafka-etc-2:
  cluster-zookeeper-1:
  cluster-zookeeper-log-1:
  cluster-zookeeper-2:
  cluster-zookeeper-log-2:
