include:
  - network.yaml

services:
  kafka-ui:
    container_name: kafka-ui
    image: ${KAFKAUI_IMAGE}
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTERS_0_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS}
      KAFKA_CLUSTERS_1_NAME: ${KAFKA_CLUSTERS_1_NAME}
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: ${KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS}
      KAFKA_CLUSTERS_2_NAME: ${KAFKA_CLUSTERS_2_NAME}
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: ${KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS}
    ports:
      - "${KAFKAUI_PORT}:8080"
    networks:
      - kafka-cluster
      - kafka-single-node
